### ISSUE TITLE
Cannot read property 'require' of undefined

### ISSUE THREAD

**Issue by murnana** [murnana/guiflow#2]
```log
C:any\dir\guiflow\node_modules\electron\dist\resources\electron.asar\renderer\api\remo…:209 Uncaught Error: Cannot read property 'require' of undefined
TypeError: Cannot read property 'require' of undefined
    at Object.<anonymous> (C:any\dir\guiflow\js\editor.js:5:40)
    at Object.<anonymous> (C:any\dir\guiflow\js\editor.js:170:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at EventEmitter.<anonymous> (C:any\dir\guiflow\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:263:70)
    at emitTwo (events.js:125:13)
    at Object.<anonymous> (C:any\dir\guiflow\js\editor.js:5:40)
    at Object.<anonymous> (C:any\dir\guiflow\js\editor.js:170:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at EventEmitter.<anonymous> (C:any\dir\guiflow\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:263:70)
    at emitTwo (events.js:125:13)
    at Object.exception (C:any\dir\guiflow\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:209:30)
    at metaToValue (C:any\dir\guiflow\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:213:28)
    at Object.exports.require (C:any\dir\guiflow\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:277:10)
    at file:///C:/any/dir/guiflow/js/script.js:32:21
```

**Comment by murnana** [comment]
duplicate murnana/guiflow#1
